# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

workspace 'WisdomProtocolDemo.xcworkspace'


target 'WisdomProtocolLeft' do
    project '../WisdomProtocolLeft/WisdomProtocolLeft.xcodeproj'
    
    pod 'SnapKit', '5.7.1'
    
    pod 'WisdomProtocol/Router', :path=>"../"
end

target 'WisdomProtocolRight' do
    project '../WisdomProtocolRight/WisdomProtocolRight.xcodeproj'
    
    pod 'SnapKit', '5.7.1'
    
    pod 'WisdomProtocol/Router', :path=>"../"
end

target 'WisdomProtocolDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WisdomProtocolDemo
  pod 'SnapKit', '5.7.1'
  
  pod 'WisdomProtocol/Router', :path=>"../"
  
#  pod 'RCBacktrace', '0.1.7'

end

